### ISSUE TITLE
Improve schema evolution process

### ISSUE THREAD

**Issue by iand** [filecoin-project/sentinel-visor#360]
### Description

Some schema migrations are extremely slow, possibly taking more than 24 hours, and will only get slower as we increase data volumes. This means we have to stop ingest and all database activity for long periods.

We need to distinguish the types of changes made to a schema:

 1. additive, non-breaking changes with no data migration (example: a new table, adding field comments, adding a view)
 2. additive, non-breaking changes with data migration (example: new materialized view, adding an index)
 3. destructive or breaking changes with no data migration (example: drop a table)
 4. destructive or breaking changes with data migration (example: change column type on populated table)

Cases 1 and 2 describe situations where the new schema still supports existing deployments of visor or querying clients such as grafana.

Cases 3 and 4 are situations where coordination effort is required to upgrade clients and visor instances.

Cases 2 and 4 are situations that could involve long periods of downtime as data is migrated.

We have discussed segregating schemas by task so they can be versioned independently but this only gives us control over the point at which we have to migrate, not the time taken. Besides, we usually want to run all tasks together so they are not very independent in reality.

We have also discussed using versioned tables but this has the disadvantage of being confusing for database users presented with multiple copies of tables. It can also lead to situations where the latest set of tables have different versions which makes it harder to keep external queries correct since every query will need to be inspected to ensure the correct versions are being used.

A simpler approach could be to have separate Postgres schemas with a versioned name containing a full set of the tables needed for visor. Updating external queries could be as simple as search and replace on the schema name, or using a user that defaults to the correct schema.

## Proposal

Introduce the notion of major schema versions and patches. Cases 2, 3 and 4 above are examples of changes that would indicate a major schema version change.  Only case 1 is considered a patch to an existing major schema.

Major schema versions should aggregate as many changes as possible with the aim of reducing the frequency of needing to halt indexing and client applications. A major schema change should be associated with at least a minor version increment for visor.

To minimise downtime and disruption, each major schema version should be deployed as a new postgres schema. All visor instances should be restarted pointing to the new schema to begin populating them with live data. Existing data is then migrated to the new tables in the background.

This means all query clients can continue using the previous schema but their views of the data will be frozen. When the data migration is complete the clients can be switched to the new schema and the old version may be removed.

The disadvantage of this approach is that we will need to maintain 2 copies of the full dataset for periods of time

Another disadvantage is that type 3 migrations, which would otherwise be quick to implement, get the overhead of a full data migration.

**Comment by iand** [comment]
Moving to a new schema and migrating data may be the best way to fix #359

**Comment by iand** [comment]
Linking to https://github.com/filecoin-project/sentinel-visor/pull/353 since it also touches schema and visor versioning

**Comment by iand** [comment]
Should note that concurrent data migrations relating to table definitions are often held up by write or read locks on tables. Migrating data to a new table is basically an insert and shouldn't be affected in the same waay.

**Comment by placer14** [comment]
Versioned schemas approach has my support. I'm thinking about how other Sentinel components might follow this pattern and the ways that seem possible include (a) implicit knowledge of which migrations to apply to which schema version, managed independently in each components own repo, or (b) manging migrations in a central repo for all components. Of the two, I think I'd prefer (a) were it not for the brittle knowledge contract of which goes where. Worth considering here?

**Comment by iand** [comment]
It's worth considering breaking the schema out into its own repo. It would make it easier to version and to reason about. There are some significant disadvantages though:

 1. It implies coupling where there might not be any. For example: currently drone and visor are independent, but if the both depended on a schema repo then there would be an indirect coupling.
 2. It adds coordination overhead. Every new repo is a new dependency relationship and requires configuration management.
 3. The schema repo would need its own release process and maybe its own staging setup.
 
The main ingest software components are independent, but it's the query clients such as grafana and apps/visualisations that depend on multiple separate schemas. Maybe that points towards having a single master schema version that these things depend on. I'm not sure.

**Comment by placer14** [comment]
Thought: If we were to break apart the application and schema concerns, I would probably include the models and DB connection/setup behavior in the repo as well. This would give us some guarantees on the runtime correctness of constraints and types. The apps would update their schema/models package as they require use of the new schema changes. The DB setup might also validate schema versions and do other checks on setup.

**Comment by placer14** [comment]
Capturing an idea shared between @iand and I. We discussed the idea of exposing layers of a schema with guarantees at each layer thus:

### Ingestion schema
Guarantee: Schema is always assumed to be immuteable with upgrades prefering to create a new schema w index instead of attempting to mutate the existing schema/index. Schema definitions are versioned and documented.
Motivation: 
+ reduce migration-time costs by not having to manipulate schema w data contained within
+ applications can manage their own schema as needed (since we're separating Ingestion concerns from Query concerns)
+ non destructive migrations allow Query concerns to be managed independently of the upgrade cycle of the underlying app (since we're not destroying old schema/data)
- requires more thought about Ingestion schema cleanup patterns

### Query schema
Guarantee: Schema guaratees to shift as seldom as is feasible to support application concerns which are drawing from Sentinel schema.
Motivation:
+ downstream apps don't have to worry (as much) about which version of Sentinel they are consuming data from
+ can potentially afford longer migration-time processes as they can be deployed with application usage patterns which are more flexible than ingestion usage patterns (which generally have required uptime 24/7/365)
+ application <-> schema guarantees can be managed on an app-by-app basis

Query schema is likely managed externally to Visor but within the Sentinel toolchain. Ingestion schema follow a similar pattern to what is in Visor today, but would avoid migration of type 3 and 4 as mentioned in the OP (which are destructive in nature).

**Comment by hsanjuan** [comment]
There are two topics mixed here:

* One is about how to provide smooth upgrade paths with minimal downtime.
* The other is about how to minimize the impact of changes on consumers of visor.

-- 
Regarding downtimes, we have two use-cases:

* Sentinel is used for monitoring network health: the database does not have to be big. It can be cleaned up (to keep 1 month-worth of data) and migrations should happen relatively quickly, which should be acceptable. Simple tooling can be provided to reduce weight (i.e. a tool to drop all rows under a certain epoch).

* Sentinel is used for analysis: the database will be very big. There is no way around having potentially long migrations. But deployment of this type should be confortable with more prolonged downtimes or ad-hoc solutions. The solution about making new schema and copying the other in the background has the problem that analysis would be badly hurt until the copying finishes, which is not much better than just waiting for a large migration to finish.
 
Doing schema management (creating a new schema, copying all data and then switching etc) is not something we have to provide as a visor-feature, but rather a deployment approach depending on the needs to be decided by operators. Perhaps our own usage and needs will force us to create tooling around this, but I am not sure if we are forced to make a choice otherwise (or let sentinel make a choice).

As a user, if I upgrade visor and there is a migration, I wouldn't expect a new schema. This gets in the way of users and access patterns that I may have configured for the other schema, potentially breaks my tools or make it seem as if the upgrade went fine when the truth is there will be a background process copying all data around, which opens more failure scenarios.

All these to say that right now, having orderly releases with well documented changes and needed migrations on-boot might be the best approach. Keeping breaking or expensive migrations for major releases etc. is something we should aim for.

--

Regarding how applications interact with Sentinel-visor and its schema and how upgrades affect it:

* I feel it is ultimately bad that applications interact with the schema directly. We should probably be providing a layer (an API?) that abstracts the schema and can offer a less prone-to-break interface. Maintaining an additional API is a complexity hurdle itself and some things like Grafana really want to speak directly against the DB.
* On the other side, I fear that maintaining multiple and application-based is a very big overload and can become a time sink.
* Having breaking changes on releases is not a bad thing per se. Consumers should know they may have to deal with this upon upgrades, like every other API. The problem is when a network upgrade or a mandatory Lotus upgrade requires a sentinel upgrade to happen or everything stops working. Thus we cannot ensure that an application will work if they keep running an old combination of visor/lotus. That is more problematic.

This last point begs the question, what is easier?

* To support an ingestion scheme and potentially multiple query-schemes (potentially per app, how would that work and where to draw the line?)
* To isolate and backport mandatory changes (lotus upgrades) to release branches using previous schemas so that there is a non-breaking upgrade path for people running older versions of visor - with older schemas?

--

Complex topic! Please keep adding thoughts.
