### ISSUE TITLE
Track verifiers and verified clients

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/sentinel-visor#434]
The verified_registry actor (`f06`) has states in actor_states as follows:

```
{"RootKey": "f080", "Verifiers": {"/": "bafy2bzacec4c4ssizldjl6qdnjl2373rcx3uft34pyhgutqfcllen72o6myj2"}, "VerifiedClients": {"/": "bafy2bzacediduhncizc4qoh726cat7ff5gflicty3fx75tqupolq4plnsqpd6"}}
```

I suspect we could be tracking verifiers and verifiedClients in their own respective tables, including information about datacaps (allowances) in each epoch. We should be able to know the list of verifiers and verifiedClients in each epoch too (perhaps another verified_registry table).

This information all comes from processing the verified registry actor.

**Comment by hsanjuan** [comment]
I'm not sure if I heard you mention that your eyes were on this @frrist ?

**Comment by frrist** [comment]
I did, but I am now hesitating since I'd like to reconsider how we diff actor states before starting in on this issue. To implement this right now, I'll need to add diffing support to Lotus. Currently, this diffing code is slow, and we might have to undo the work done to complete this issue to improve it. I have filed https://github.com/filecoin-project/sentinel-visor/issues/504 to discuss this more.
