### ISSUE TITLE
Capture Miner Deadlines

### ISSUE THREAD

**Issue by placer14** [filecoin-project/sentinel-visor#61]
In order to understand WindowPoSt commitments and how they are being maintained on-chain, we will extract StorageMinerActor.Deadlines and its related data into Sentinel schema for monitoring and analysis.

Requirements:
1. Produced schema should express ability to query for
  a. PoSts expected (per miner, per sector, per deadline CID (unsure how to uniquely identify deadlines))
  b. Messages (as well as other mechanisms required by Miner to fulfill successful PoSt) which satisfy expected PoSts

Deliverables:
- [ ] Migration which relates the following objects `Miners` --hasmany-> `Deadlines` --hasmany-> `Partitions` --hasmany-> `Sectors`
- [ ] StorageMinerActor extractors which support the schema produced in the previous migration
- [ ] Example query (or pseudoquery) expressing ability to achieve R1 (a and b)

**Comment by frrist** [comment]
@willscott did #74 resolve this? If not, what is left to do here?

**Comment by willscott** [comment]
that's correct:
* the current table is populated when relevant miner state changes across tipsets. this is the correct and sufficient trigger.
* When this happens, we find all relevant messages, and populate message, miner, and affected sectors.
* Miner changes may also be unrelated to messages, and be due to cron-based expiry of post windows. we initially planned to populate these with an empty message ID. It is somewhat unclear to me how valuable that additional signal is.

is the p1 adding this additional set of rows, or having a generated table and seeing if it's good enough for windowPoSt analysis?
